# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0033_auto_20190312_1742'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bepress', '0002_auto_20190312_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedArticleAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bepress_importedarticleauthor', to='submission.Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bepress_importedarticleauthor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='importedarticleauthor',
            unique_together=set([('article', 'author')]),
        ),
    ]
