# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0034_auto_20190416_1009'),
        ('bepress', '0003_auto_20190312_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedarticle',
            name='dump_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='importedarticle',
            unique_together=set([('article', 'bepress_id', 'dump_name')]),
        ),
    ]
