# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-07-25 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_auto_20220725_1704'),
        ('bepress', '0004_auto_20190619_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bepress_id', models.PositiveIntegerField()),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Book')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Chapter')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='importedchapter',
            unique_together=set([('book', 'chapter', 'bepress_id')]),
        ),
    ]
